### PR TITLE
[ADD] RST versions of the current legal documents

### PR DESCRIPTION
**Pull request by max3903**
Add:
* Bylaws
* ECLA
* ICLA

Warning: 

Links on https://odoo-community.org/page/cla must be updated to point to the pdf at the root directory.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by clonedagain** [comment]
:+1:
Maybe a short note should be added in the header of the documents to remind that a vote is needed to amend them, not just a PR.

**Comment by max3903** [comment]
@clonedagain it's done in the README.rst:
https://github.com/OCA/odoo-community.org/pull/20/files#diff-88b99bb28683bd5b7e3a204826ead112R11

**Comment by Yajo** [comment]
Obviously I have not tested this, but seems a great initiative, thank you @max3903 :+1:

**Comment by jgrandguillaume** [comment]
:+1:

**Pull request merged**
