### PR TITLE
Fix bylaws typos

### PR DESCRIPTION
**Pull request by SirAionTech**
I was reading it and noticed a few typos so I reviewed the whole page, enjoy!

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]

**Comment by SirAionTech** [comment]
Can someone merge this? Thanks!
Looking at https://oca.github.io/repo-maintainer-conf/odoo.html#the-odoo-community-association-website, someone from @OCA/board is needed.

**Comment by vdewulf** [comment]
hello,
I just reviewed the fixes, seems good!
I'll check with the board on Wednesday meeting to have someone validate this.
Thanks

**Review by vdewulf — APPROVED** [review]

**Comment by sbidoul** [comment]
Just typos, no material change so I guess this is fine.

**Comment by sbidoul** [comment]
Thanks Simone!

**Pull request merged**
