### PR TITLE
Advertise space instead of community

### PR DESCRIPTION
**Pull request by Yajo**
Communities are old, spaces are the new thing. And we have one.

https://element.io/blog/spaces-the-next-frontier/

@moduon

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
👍

**Comment by Yajo** [comment]
Merge? cc @sbidoul @pedrobaeza

**Comment by pedrobaeza** [comment]
I don't have the rights for merging in this repo. @simahawk I applied to this PSC on the mailing list. Maybe you can check it?

**Comment by simahawk** [comment]
@pedrobaeza there's no PSC here as far as I see. Only @OCA/board has rights.

**Comment by pedrobaeza** [comment]
OK, I thought this was included in the same PSC as the rest of the tools (maintainer-tools, maintainer-quality-tools, etc).

**Pull request merged**
