### PR TITLE
Use generic CI references

### PR DESCRIPTION
**Pull request by SirAionTech**
Travis is no more used

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]

**Review by pedrobaeza — COMMENTED** [review]
Please comment about Codecov checks not being mandatory, which is a recurrent question among beginners.

**Review by luisg123v — CHANGES_REQUESTED** [review]
Please provide commit descriptions.

**Comment by luisg123v** [comment]
> I understand about being neutral in the denominations, but not sure if people is going to associate coverage <> Codecov. Let's put the exact reference and modify it if this changes in the future.

Maybe:

coverage  → coverage checks

That way, it will be explicit it refers to the CI checks regarding coverage.

Or in fault:


coverage checks (currently done by codecov)

**Comment by SirAionTech** [comment]
Should be all done.

The first time "coverage CI" is mentioned it is a little verbose to explain that it is done with Codecov.
The following occurrences only say "coverage CI".

Added descriptions to all commits.

Also noticed that Runbot was still there.

**Review by pedrobaeza — APPROVED** [review]

**Review by luisg123v — CHANGES_REQUESTED** [review]
Could you leave a blank line between commit title and description, please?

**Pull request merged**
