### PR TITLE
Update CONTRIBUTING.rst with translations

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Review by SimoRubi — APPROVED** [review]

**Review by primes2h — APPROVED** [review]
LGTM :+1:

**Review by luisg123v — CHANGES_REQUESTED** [review]
I like this clarification. However, by just reading this, it's not clear (at least not to me) that `.pot` files should actually be modified when adding new terms.

I'd clarify that, mentioning also when new terms are added, they should be placed in their correct position withing the `.pot` file (i.e. same position they take when re-exporting translations).

**Comment by pedrobaeza** [comment]
POT are generated automatically by the bot, so no need to do it. Also this redaction is not correct. You are allowed to modify translations when migrating a module. The key is that the module doesn't exist yet on the repo, and thus, there's no translation yet on Transifex that can provoke conflict if it's updated meanwhile the PR lifecycle.

**Comment by SimoRubi** [comment]
> You are allowed to modify translations when migrating a module. The key is that the module doesn't exist yet on the repo, and thus, there's no translation yet on Transifex that can provoke conflict if it's updated meanwhile the PR lifecycle.

Yes I noticed that too but I think that's why it says
> Pull requests should never directly **modify** ``.po`` files

but it allows PRs that create new `.po` files that is what happens in migration PRs and PRs that add new modules in general.
Maybe a little clarification might be added stating something like
> Pull requests creating new modules can add their own `.po*` files

**Comment by pedrobaeza** [comment]
Yes, good point.

**Comment by eLBati** [comment]
Extended a bit. Thanks!

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
